feat: 찜한 음식점 조회 api
2024-celuveat/server pull request #20
Opened 2024-08-01 15:23 UTC by TaeyeonRoyce

2024-08-02 04:21 UTC, shin-mallang requested changes
우선 바빠서 중간정보..? 봤어!!!

2024-08-02 04:21 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/adapter/out/persistence/CelebrityPersistenceAdapter.kt
> +    override fun findVisitedCelebritiesByRestaurants(restaurantIds: List<Long>): Map<Long, List<Celebrity>> {
이름이 좀 헷갈리는 것 같기도 하고... 괜찮나?

2024-08-02 04:21 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/adapter/out/persistence/entity/VideoFeaturedRestaurantJpaEntity.kt
> +class VideoFeaturedRestaurantJpaEntity(
영상 - 비디오 매핑인거 같은데 Featured 로 명명한 이유가 있나요?
제가 영어를 잘 못해서..

2024-08-02 04:21 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/adapter/out/persistence/entity/VideoFeaturedRestaurantJpaRepository.kt
> +        JOIN yc.celebrity c
조인 조건 (on 절) 없는 이유??
JPQL 이라 암묵적으로 들어가나?

2024-08-02 04:21 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/restaurant/adapter/in/rest/RestaurantApi.kt
> +        @RequestParam("size") size: Int?,
```kotlin
@PageableDefault pageable: Pageable
```
이거 되지 않나여?

2024-08-02 05:57 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/celeb/adapter/out/persistence/entity/VideoFeaturedRestaurantJpaEntity.kt
> +class VideoFeaturedRestaurantJpaEntity(
영상에 나온 음식점을 표현한거였어!

2024-08-02 05:58 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/celeb/adapter/out/persistence/entity/VideoFeaturedRestaurantJpaRepository.kt
> +        JOIN yc.celebrity c
JQPL이라 id로 알아서 on절이 들어가요!

2024-08-02 06:02 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/restaurant/adapter/in/rest/RestaurantApi.kt
> +        @RequestParam("size") size: Int?,
돼요!
pageable로 바로 받는게 나을 듯!

2024-08-03 07:02 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/celeb/adapter/out/persistence/entity/VideoFeaturedRestaurantJpaEntity.kt
> +class VideoFeaturedRestaurantJpaEntity(
[ba96825](https://github.com/2024-celuveat/server/pull/20/commits/ba96825d1cf93f2dc04fcf273a683fa58e0d3b73)
RestaurantInVideo로 변경했어!

2024-08-03 07:03 UTC, merged