feat: 관심 셀럽 추가삭제 api
2024-celuveat/server pull request #27
Opened 2024-08-05 06:18 UTC by TaeyeonRoyce

# 관련 태스크
- closed #22 
---
#23 와 비슷한 구조로 작성하였습니다!

2024-08-08 09:25 UTC, shin-mallang requested changes
고생했어!!!

2024-08-08 09:25 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/adapter/in/rest/CelebrityApi.kt
> +    @SecurityRequirement(name = "JWT")
클래스 상단에 하나만 해도 될 것 같아!

2024-08-08 09:25 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/adapter/out/persistence/CelebrityPersistenceAdapter.kt
> +        validateExistence(memberId, celebrityId)
이거 밸리데이션 지우고, entity 자체에 unique constraints 거는거 어때?

2024-08-08 09:25 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/application/port/out/DeleteCelebrityPort.kt
> +interface DeleteCelebrityPort {
Interested 붙여줘야 하지 않을까?
셀럽이랑 관심 셀럽은 명확히 분리되야 할 거 같아(save 도 마찬가지)

2024-08-08 09:25 UTC, shin-mallang commented on src/test/kotlin/com/celuveat/celeb/adapter/in/rest/CelebrityControllerTest.kt
>  class CelebrityControllerTest(
controller 테스트는 무의미한 것 같다는 생각 들지않아..?

2024-08-08 09:35 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/celeb/adapter/out/persistence/CelebrityPersistenceAdapter.kt
> +        validateExistence(memberId, celebrityId)
entity에 unique키 두는거 좋네
유니크 제약조건 예외 핸들링 방식으로 처리해둘게

2024-08-08 09:38 UTC, TaeyeonRoyce commented on src/test/kotlin/com/celuveat/celeb/adapter/in/rest/CelebrityControllerTest.kt
>  class CelebrityControllerTest(
header나 pathvariable 같은 요청 파라미터 검증에도 좋고 응답 보는용으로 괜찮은거 같은데..
작성하는 것도 오래 걸리진 않아서 계속 작성하고 있었어

2024-08-08 09:39 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/celeb/application/port/out/DeleteCelebrityPort.kt
> +interface DeleteCelebrityPort {
중간테이블 객체를 안뒀어서 여기서 처리했는데
추가할거면 구분해서 두는게 낫겠다

2024-08-09 05:39 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/celeb/adapter/in/rest/CelebrityApi.kt
> +    @SecurityRequirement(name = "JWT")
이거 바로 다음 PR에서 다시 분리해야 해서 놔둘게욥...!

2024-08-09 09:57 UTC, shin-mallang commented on src/test/kotlin/com/celuveat/celeb/adapter/in/rest/CelebrityControllerTest.kt
>  class CelebrityControllerTest(
음음 글쿤 오키오키!

2024-08-09 11:53 UTC, shin-mallang approved these changes
고생고생!!! 늦어서 먄!!

2024-08-09 14:38 UTC, merged