feat: 리뷰 관련 usecase 작성
2024-celuveat/server pull request #31
Opened 2024-08-06 13:00 UTC by shin-mallang

- 임시 PR 입니다.
- 리뷰 관련 UseCase 작성했습니다. 확인 부탁드려요!
- 리뷰 작성, 수정, 삭제, 조회, 리뷰 도움돼요, 도움돼요 제거 기능 구현하였습니다.
- 코드량 빡세네요...

2024-08-08 03:59 UTC, TaeyeonRoyce reviewed
리뷰 남겼습니다~
PR마무리 해주세욥

2024-08-08 03:59 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/adapter/out/persistence/ReviewPersistenceAdapter.kt
> +        val LATEST_ID_SORTER = Sort.by("id").descending()
최신순이라 그냥 id로 했는데 `createdAt`으로 변경해도 될 듯요

2024-08-08 03:59 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/adapter/out/persistence/entity/HelpfulReviewJpaEntity.kt
> +    val clicker: MemberJpaEntity,
그냥 member로 하는게 낫지 않아?
jpa entity는 DB관점으로 보고 있는데 member table에 맞게 정의하는 게 낫을 거 같아서!

2024-08-08 03:59 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/application/port/in/command/WriteReviewCommand.kt
> +    var star: Star,
이미지도 고려해야할 것 같아유

2024-08-08 03:59 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/application/port/ReviewService.kt
> +        deleteHelpfulReviewPort.deleteHelpfulReview(helpfulReview)
helpfulReview.unClick()으로
review의 `helps -= 1`이 로직이 DB에 반영이 되나요?

2024-08-08 03:59 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/domain/HelpfulReview.kt
> +) {
중간테이블처럼 쓰이는 애도 도메인으로 두는게 낫나?
관심쪽은 따로 안만들었는데 이 방법도 좋아보이네

2024-08-08 09:27 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/review/application/port/ReviewService.kt
> +        deleteHelpfulReviewPort.deleteHelpfulReview(helpfulReview)
아 위에 review save 추가 잊었넹
save도 마찬가지로 추가해야할듯
고마워!!

2024-08-08 09:28 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/review/domain/HelpfulReview.kt
> +) {
웅 나는 일단 둬봤어!!!
나쁘지 않을 것 같아!

2024-08-08 09:28 UTC, shin-mallang reviewed
감사합니다..

2024-08-11 06:28 UTC, TaeyeonRoyce requested changes
고생하셨어요~!
리뷰 남겼는데 확인해주세용

2024-08-11 06:28 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/adapter/in/rest/ReviewApi.kt
> +    )
리뷰 작성엔 필요 없을 것 같아요!

2024-08-11 06:28 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/adapter/in/rest/ReviewApi.kt
> +    @PostMapping("/help/{reviewId}")
```suggestion
    @PostMapping("/helpful/{reviewId}")
```
`helpful`은 어떨까요

2024-08-11 06:28 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/adapter/out/persistence/entity/HelpfulReviewJpaEntity.kt
> +class HelpfulReviewJpaEntity(
얘도 unique 제약 조건 추가하죠!

2024-08-11 06:28 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/adapter/out/persistence/entity/ReviewJpaEntity.kt
> +    }
이 부분 설명 부탁드려요...!

2024-08-11 06:28 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/application/port/in/ReadReviewListUseCase.kt
> +interface ReadReviewListUseCase {
```suggestion
interface ReadReviewsUseCase {
```
복수형 표현으로 사용하고 있습니다!

2024-08-11 06:28 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/application/port/ReviewService.kt
> +        saveHelpfulReviewPort.save(helpfulReview)
굿👍

2024-08-11 06:28 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/domain/Star.kt
> +                ?: throw IllegalArgumentException("star value is must be 1 ~ 5, but current is $score") // TODO throw internal server error
예외 감싸야 할 것 같습니당

2024-08-11 06:28 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/exception/ReviewExceptions.kt
> +data object AlreadyClickHelpfulReviewException : ReviewExceptions(HttpStatus.NOT_FOUND, "해당 리뷰에 아미 '도움돼요'를 클릭하였습니다.") {
```suggestion
data object AlreadyClickHelpfulReviewException : ReviewExceptions(HttpStatus.BAD_REQUEST, "해당 리뷰에 아미 '도움돼요'를 클릭하였습니다.") {
```
400으로 처리하는게 낫지 않아요?

2024-08-11 06:28 UTC, TaeyeonRoyce commented on src/test/kotlin/com/celuveat/review/domain/ReviewTest.kt
> +            }
Then 블록은 일부러 안한건가요?!

2024-08-11 06:28 UTC, TaeyeonRoyce commented on src/test/kotlin/com/celuveat/review/domain/ReviewTest.kt
> +@DisplayName("리뷰는")
얘만 @DisplayName이 달려있는데... 필요한가요?
코드 일관성 있게 유지하려면 다 해야할 것 같은데, 같이 정해보죠..!

2024-08-11 06:28 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/domain/ReviewImage.kt
> +data class ReviewImage(
id가 빠졌어요!

2024-08-11 06:30 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/review/adapter/in/rest/ReviewApi.kt
> +    )
리뷰 작성에 넣어버렸군요... 지송합니다

2024-08-11 06:30 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/review/adapter/out/persistence/entity/HelpfulReviewJpaEntity.kt
> +class HelpfulReviewJpaEntity(
좋습니다~

2024-08-11 06:31 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/review/adapter/out/persistence/entity/ReviewJpaEntity.kt
> +    }
string 으로 받아서 reviewImage 만들려 했어요!
(외부에서 만들어 전달하는거 대신)

2024-08-11 06:31 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/review/exception/ReviewExceptions.kt
> +data object AlreadyClickHelpfulReviewException : ReviewExceptions(HttpStatus.NOT_FOUND, "해당 리뷰에 아미 '도움돼요'를 클릭하였습니다.") {
중복이라 confict 생각했는데 400으로 갈까요?

2024-08-11 06:32 UTC, shin-mallang commented on src/test/kotlin/com/celuveat/review/domain/ReviewTest.kt
> +            }
should not thrown 에서 then을 어떻게 해야항 지 몰라서 안했습니다!

2024-08-11 06:32 UTC, shin-mallang commented on src/test/kotlin/com/celuveat/review/domain/ReviewTest.kt
> +@DisplayName("리뷰는")
아 맞네요 이거 지우겠습니다

2024-08-11 06:33 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/review/domain/ReviewImage.kt
> +data class ReviewImage(
id 여기서는 필요 없어서 안 넣었습니다!

2024-08-11 06:35 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/exception/ReviewExceptions.kt
> +data object AlreadyClickHelpfulReviewException : ReviewExceptions(HttpStatus.NOT_FOUND, "해당 리뷰에 아미 '도움돼요'를 클릭하였습니다.") {
409 conflict도 좋습니다~!

2024-08-13 02:38 UTC, TaeyeonRoyce reviewed
고생하셨어요~! 코멘트만 확인해주세요!

2024-08-13 02:38 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/adapter/in/rest/ReviewApi.kt
> +    )
이건 리팩토링에서 한번에 지울게요~

2024-08-13 02:38 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/review/adapter/in/rest/response/ReviewResponses.kt
> +data class ReviewPreviewResponse(
유저의 도움돼요 클릭여부도 포함되어야 할 것 같습니다!

2024-08-13 13:30 UTC, TaeyeonRoyce approved these changes
고생하셨습니다~!

2024-08-13 13:31 UTC, merged