feat: best셀럽 및 음식점 api
2024-celuveat/server pull request #34
Opened 2024-08-09 15:07 UTC by TaeyeonRoyce

# 관련 태스크
- closed #28
---
![Screenshot 2024-08-10 at 00 00 01](https://github.com/user-attachments/assets/c5e798f7-3457-4bb1-9914-4d72257627c4)
Best 셀럽 조회에 대한 API를 개발하였습니다.
제안 드린 것 처럼 셀럽의 음식점 조회는 API를 따로 분리하였습니다! 

작업을 하는 과정에서 몇가지 추가적인 작업이 이루어졌는데요.
1. @DataJpaTest[시 롤백이 되지 않는 오류 해결](https://github.com/2024-celuveat/server/commit/421e9eca6180f3ba0a8d907ffd9e65813d517aff)
Kotest와 DataJpaTest 사용시 예상하는 테스트 라이프 사이클에 따라 @Transactional 롤백이 되지 않는 이슈가 있습니다.
- ref: https://github.com/kotest/kotest/pull/1684
해당 문서 참고하여 전체적으로 적용할 수 있도록 구성하였습니다!!

2. [refactor: 관심 추가한 음식점 (InterestedRestaurant) 도메인으로 분리](https://github.com/2024-celuveat/server/commit/8b9de484e004402ffcaf02d9dc0e976718244917)
#27 리뷰 남겨주신 것처럼 중간테이블 객체도 도메인으로 분리하는 작업을 하였습니다.

3. [refactor: 회원/비회원 인증 처리 AuthContext로 통합](https://github.com/2024-celuveat/server/commit/092399b2231e0a75c0c0556a98d0499caf7ec18e)
셀럽으로 음식점 조회시 회원/비회원도 모두 요청 가능한 API인데요.
회원 전용인 `AuthId`가 아닌, 한번 포장한 객체로 변환하여 전체적으로 적용 하였습니당...!

2024-08-09 15:23 UTC, shin-mallang requested changes
고생했습니다 형님!!!!!!!!

2024-08-09 15:23 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/adapter/in/rest/CelebrityApi.kt
> +        @Auth auth: AuthContext,
@SecurityRequirement(name = "JWT") 여기 붙어야 할 것 같아요!
아니면 그냥 class 최상단에?

2024-08-09 15:23 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/adapter/in/rest/CelebrityApi.kt
> +    fun readBestCelebrities(): List<SimpleCelebrityResponse>
앞으로 그냥
단일 조회면 `Simple도메인Result`, `Simple도메인Response`
다중 조회면 `도메인복수형Result`, `도메인복수형Response` 로 용어 통일 합시당

2024-08-09 15:23 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/adapter/in/rest/CelebrityController.kt
> +    private val readBestCelebritiesUseCase: ReadBestCelebritiesUseCase,
위에 `GetInterestedCelebritiesUseCase` 도 read 로 바꿔줘야 하지 않을까용

2024-08-09 15:23 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/adapter/in/rest/response/CelebrityResponse.kt
> +        fun from(result: YoutubeContentResult): YoutubeContentResponse {
good

2024-08-09 15:23 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/adapter/out/persistence/entity/CelebrityJpaRepository.kt
> +            ORDER BY yc.subscriberCount DESC LIMIT 15
15 그냥 박는거... 괜찮나??

2024-08-09 15:23 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/application/CelebrityService.kt
> +    private val findCelebritiesPort: FindCelebritiesPort,
persistence layer 에서는 find 로???
혹시 그냥 다 read 어떤지?

2024-08-09 15:23 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/application/CelebrityService.kt
>      @Transactional
tx 필요한가요 여기

2024-08-09 15:23 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/restaurant/adapter/out/persistence/InterestedRestaurantPersistenceAdapter.kt
> +    private fun validateExistence(
adapter에서 validate 제거..!

2024-08-09 15:23 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/restaurant/application/RestaurantQueryService.kt
> +    override fun readVisitedRestaurant(query: ReadVisitedRestaurantQuery): SliceResult<RestaurantPreviewResult> {
'셀럽' 이 방문한 을 명확하게 해줬으면 좋겠어!

2024-08-09 15:32 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/celeb/adapter/in/rest/CelebrityApi.kt
> +    fun readBestCelebrities(): List<SimpleCelebrityResponse>
단일의 경우 Simple이 아니라 `Single도메인Result`아닌가요?!
Simple은 말그대로 단순(부분) 정보인 경우에 사용했어요!

2024-08-09 15:33 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/celeb/adapter/out/persistence/entity/CelebrityJpaRepository.kt
> +            ORDER BY yc.subscriberCount DESC LIMIT 15
무한 스크롤도 아니라서 괜찮을 것 같습니다...!

2024-08-09 15:36 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/celeb/application/CelebrityService.kt
> +    private val findCelebritiesPort: FindCelebritiesPort,
persistence layer는 find 쓰긴 했는데 다 통일하는게 나을까요?!

2024-08-09 15:39 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/celeb/application/CelebrityService.kt
>      @Transactional
아아 쓰기 작업에 대해선 Adapter에서 다 붙히기로 했던거랑 헷갈렸어유
Adapter에 추가할게요!

2024-08-09 16:05 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/adapter/in/rest/CelebrityApi.kt
> +    fun readBestCelebrities(): List<SimpleCelebrityResponse>
Simple, Single, Preview.. 등등 이런거 한번 usecase 정리하면 좋을듯합니다.

2024-08-09 16:06 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/adapter/out/persistence/entity/CelebrityJpaRepository.kt
> +            ORDER BY yc.subscriberCount DESC LIMIT 15
메서드 이름 자체에 top15 를 넣어주거나, 주석 달아주는게 나중에 봤을 때 명확할 것 같아용

2024-08-09 16:51 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/celeb/adapter/in/rest/CelebrityApi.kt
> +        @Auth auth: AuthContext,
붙어있어요!
인증 필요 없는 요청도 있어서 메서드 단위로 할게요!

2024-08-10 00:36 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/celeb/application/CelebrityService.kt
> +    private val findCelebritiesPort: FindCelebritiesPort,
통일 하는게 머리는 덜 아플 것 같아요!

2024-08-10 06:12 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/celeb/application/CelebrityService.kt
> +    private val findCelebritiesPort: FindCelebritiesPort,
통일 시켰습니다~! [58baf2e](https://github.com/2024-celuveat/server/pull/34/commits/58baf2ebfd6b75e449421a970aa002bed07eed54)

2024-08-10 13:04 UTC, shin-mallang approved these changes
고생하셨습니다~

2024-08-10 13:04 UTC, merged