[Draft] feature: 카카오 로그인 구현
2024-celuveat/server pull request #4
Opened 2024-07-11 14:56 UTC by TaeyeonRoyce

코드 구조에 대한 중간점검 부탁드려유~

`OAuth`를 통해 로그인/회원가입 하는 기능에 관련한 PR인데, `외부API`로의 요청을 `port.out`으로 정의해봤어

구조 다이어그램
![Screenshot 2024-07-11 at 23 50 50](https://github.com/2024-celuveat/server/assets/90550065/643cadb4-f0eb-4f37-ad4c-90792b09caf3)

구조에 대한 피드백 부탁드립니다. 기능, 테스트, 동작 구현은 추후에 완성해서 올릴 예정!

몇가지 고민이 있어요
1. OAuth 관련 로직을 Member 개념에 포함시켜도 될지?
-> `회원`은 소셜 로그인으로만 생성 되어서 굳이 `auth`로 분리시킬 필요가 있나 싶었습니다. 우선은 member 패키지 내부에 정의되어 있어요.
2. `OAuth 로그인` 대신 `Social 로그인`으로 기술적인 것 보단 요구사항 용어로 사용하면 어떨지?

2024-07-11 23:10 UTC, shin-mallang requested changes

2024-07-11 23:10 UTC, shin-mallang commented on build.gradle.kts
> +    implementation("io.netty:netty-resolver-dns-native-macos:4.1.68.Final:osx-aarch_64")
저희 쓰는 버전부터는 webclient 대신 restClient로 사용 가능해서 해당 의존성 필요없습니당!

2024-07-11 23:10 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/common/adapter/out/persistence/entity/BaseEntity.kt
> +abstract class BaseEntity {
사소하긴한데
네이밍 요거 참고해보면 어때?
[도메인 주도 설계 사실과 오해](https://github.com/eternity-oop/DDD-essence-jdbc-part2/tree/main/src/main/java/org/eternity/base/domain)

2024-07-11 23:10 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/member/adapter/out/oauth/config/OAuthApiInterfaceConfig.kt
> +        return HttpServiceProxyFactory.builderFor(
defaultStatusHandler 사용해서
예외 시 로깅 추가해주면 좋을 것 같아!

2024-07-11 23:10 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/member/application/port/out/OAuthRequestPort.kt
> +}
1개 포트에서 두 가지 역할을 수행해도 상관없는건가?

2024-07-11 23:10 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/member/application/OAuthService.kt
> +        val member = userInfo.toMember()
생각해보니 이 3 과정은 이곳에서 분리되어 처리할 필요가 없는 것 같아!

val member = oAuthRequestPort.fetchMember(serverType, authCode) 만으로 충분할 듯!
그리고 그렇게 되면 OAuthRequestPort도
FetchOauthMemberPort로 바뀌어도 될 듯?

2024-07-11 23:23 UTC, shin-mallang commented
구조는 넘 좋은 것 같습니당!
> OAuth 관련 로직을 Member 개념에 포함시켜도 될지?
-> 회원은 소셜 로그인으로만 생성 되어서 굳이 auth로 분리시킬 필요가 있나 싶었습니다. 우선은 member 패키지 내부에 정의되어 있어요.

좋다고 생각합니다~

> OAuth 로그인 대신 Social 로그인으로 기술적인 것 보단 요구사항 용어로 사용하면 어떨지?
OAuthSignUpUsecase -> SocialLoginUsecase 의미하는 거라면 좋아요!
OAuthService 부터는 그대로 가져가도 좋을 것 같습니다~? (아니면 이것도 변경하고 싶으신걸까용)

2024-07-12 05:11 UTC, TaeyeonRoyce commented on build.gradle.kts
> +    implementation("io.netty:netty-resolver-dns-native-macos:4.1.68.Final:osx-aarch_64")
오 Spring 6.1부터 구현체가 더 생겼군요. 좋은 정보 감사합니다~!
불필요한 의존성 빼고, RestClient로 변경해둘게유

2024-07-12 05:42 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/member/application/OAuthService.kt
> +        val member = userInfo.toMember()
좋아. OAuth 과정마다 나눠서 만들면 테스트도 그렇고 나중에 활용하기 좋지 않을까 생각했는데, 한번에 `Member`를 받는게 더 좋을 것 같네. 정의한 Port의 의미도 명확해지고!👍

2024-07-12 05:50 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/member/application/port/out/OAuthRequestPort.kt
> +}
응집도만 맞으면 해도 괜찮다고 생각해!
포트에서 무조건 하나의 역할을 하기엔 애매한 부분들이 있는것 같아.

[회원 조회] 역할을 드러내는 포트를 정의할 때, ex)`FindMemberPort` 처럼 아웃고잉 포트에서의 책임은 회원 조회잖아.
`findById()`, `findByOAuthId()`, `findByNickname()` 정도는 같이 정의해도 괜찮지 않을까?

무조건 하나의 역할을 고수하기 보단, 정의한 포트의 책임에 맞게 역할을 부여하는건 어때? 물론 너무 많은 역할을 지는건 지양하고!

2024-07-12 06:49 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/member/application/port/out/OAuthRequestPort.kt
> +}
오 좋은 것 같아!
그런데 그렇게 치면 save랑 delete 도 persistence 의 관점에서 같이 가져갈 수 있지 않을까?

2024-07-12 12:16 UTC, TaeyeonRoyce commented
@shin-mallang 
https://github.com/2024-celuveat/server/pull/4/commits/fecc00b41dffc76fee57e2a8b636180a879b22ee 공통화 시도중

2024-07-12 16:19 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/member/application/port/out/OAuthRequestPort.kt
> +}
port의 역할 범위에 맞춰서 그럴 수 있을 것 같아!
이름이 `MemberPersistencePort` 이러면 CRUD를 다 담당하게 되는..?
정하기 나름이지 않을까 싶어

2024-07-12 18:05 UTC, shin-mallang commented
@TaeyeonRoyce 
- OAuth -> SocialLogin 으로 용어 다 바꿨구,
- 로그인 후 JWT 생성하는 코드까지 작성해봤어 (구조 헷갈려서 좀 걸렸어..)
- 그리고 SocialLoginToken & SocialLoginInfoResponse 클래스가 adapter 에서만 사용되는데 port 에 있길래 위치 옮겼어!

2024-07-13 06:46 UTC, TaeyeonRoyce reviewed
고생하셨습니다~
TODO 이어서 할게여

2024-07-13 06:46 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/auth/application/TokenService.kt
> +    }
companion object 는 가장 아래에 배치하는 컨벤션으로 가자!
https://kotlinlang.org/docs/coding-conventions.html#class-layout

2024-07-13 06:46 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/auth/adaptor/out/TokenAdaptor.kt
> +                .build()
별 차이는 없는데 아래처럼 외부에서 반환해도 좋을 것 같아
```suggestion
        return try {
            Jwts.parser()
                .verifyWith(secretKey)
                .build()
```

2024-07-13 06:46 UTC, TaeyeonRoyce commented on src/test/kotlin/com/celuveat/support/FixtureMonkeyConfiguration.kt
> +val sut: FixtureMonkey = FixtureMonkey.builder()
굿👍

2024-07-13 08:41 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/auth/application/TokenService.kt
> +    }
오홍 좋아용

2024-07-13 08:42 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/auth/adaptor/out/TokenAdaptor.kt
> +                .build()
오.. 되는지 처음 알았어..
자바도 되나 저거

2024-07-13 14:45 UTC, TaeyeonRoyce commented
[추가 커밋](https://github.com/2024-celuveat/server/pull/4/files/68f6f23a8fad9e010630df9fe1350e50932416c0..53f51479e6ff5e8ce09e9ad3d62a464927df3ca2) 리뷰 요청드려요!

Api Test의 경우 @WebMvcTest를 사용하여 필요한 부분만 구성 되도록 Slice 하였습니다. MockMvc를 통해 검증했어요!

2024-07-13 14:49 UTC, TaeyeonRoyce commented on build.gradle.kts
> +    testImplementation("com.ninja-squad:springmockk:4.0.2")
`@MockkBean` 을 사용하기 위해 추가하였습니다.
Mockk에서는 MockBean 처럼 사용할 수 있는 기능을 못찾았었어요.
가장 직관적으로 사용할 수 있고, 자주 사용 되는 라이브러리를 추가했습니다!

ref)
- https://techblog.woowahan.com/5825/
- https://github.com/Ninja-Squad/springmockk

2024-07-13 15:02 UTC, shin-mallang approved these changes
진짜 고생했습니다!!!!
간단하게 리뷰 남겼어!

2024-07-13 15:02 UTC, shin-mallang commented on build.gradle.kts
> +    testImplementation("com.ninja-squad:springmockk:4.0.2")
굳!!!!!!1

2024-07-13 15:02 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/auth/adaptor/in/rest/AuthMember.kt
> +annotation class AuthMember
AuthMemberId 나
AuthId 는 어떤 거 같나요?
(사실 지금도 좋긴 한데, member 인데 Long 인게 살짝..?)

2024-07-13 15:02 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/auth/adaptor/out/TokenProperty.kt
> +@ConfigurationProperties(prefix = "jwt")  // TODO application 파일에 추가
TODO 지워도 될 것 같아요!

2024-07-13 15:02 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/auth/exception/JwtExceptions.kt
> +sealed class JwtExceptions(
너무좋다...!

2024-07-13 15:02 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/common/adapter/out/rest/WebExtensions.kt
> +}
코틀린 초고수...

2024-07-13 15:02 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/common/exception/ExceptionControllerAdvice.kt
> +        )
메세지 넘 깔끔한 것 같아요

2024-07-13 15:02 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/member/adapter/out/oauth/FetchSocialMemberAdapter.kt
> +        val socialLoginInfo = socialLoginClient.fetchMemberInfo(socialLoginToken.accessToken)
아 이거 전에 말했던 거 같은데, fetchMemberInfo 내에서  fetchAccessToken 작업을 내부적으로 수행하는 식으로 처리하는건 어떤 것 같아?

2024-07-13 15:02 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/member/adapter/out/oauth/config/SocialLoginApiClientConfig.kt
> +                })
넘 깔끔한듯요 !

2024-07-13 15:02 UTC, shin-mallang commented on src/main/kotlin/com/celuveat/member/adapter/out/oauth/config/SocialLoginApiClientConfig.kt
> +                    log.error("Server Error Message={}", String(response.body.readAllBytes()))
"External Api Server Error ~~" 는 어떨지?

2024-07-13 15:02 UTC, shin-mallang commented on src/test/kotlin/com/celuveat/member/adapter/in/rest/SocialLoginControllerTest.kt
> +) : FunSpec({
FunSpec 을 쓴 이유가 있나요?

2024-07-13 15:06 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/auth/adaptor/in/rest/AuthMember.kt
> +annotation class AuthMember
어 맞네! Long 타입인데 `AuthId`로 변경할게!

2024-07-13 15:07 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/member/adapter/out/oauth/FetchSocialMemberAdapter.kt
> +        val socialLoginInfo = socialLoginClient.fetchMemberInfo(socialLoginToken.accessToken)
아아 포트에서만 합쳐뒀었네...ㅎㅋㅎㅋ 좋아좋아!

2024-07-13 15:07 UTC, TaeyeonRoyce commented on src/main/kotlin/com/celuveat/member/adapter/out/oauth/config/SocialLoginApiClientConfig.kt
> +                    log.error("Server Error Message={}", String(response.body.readAllBytes()))
좋습니다~! 외부 서버 오류로 분류해서 로깅하는게 훨 낫네

2024-07-13 15:10 UTC, TaeyeonRoyce commented on src/test/kotlin/com/celuveat/member/adapter/in/rest/SocialLoginControllerTest.kt
> +) : FunSpec({
처음엔 BehaviorSpec로 Given/When/Then으로 구성했었는데,
mockMvc로 테스트를 하니깐 한 블럭에서 요청이랑 검증이 동시에 이루어지더라고.
```kotlin
mockMvc.get()
    .andExpect(...)
```
API 테스트에서만 FunSpec 스타일로 context - test 형태로 구성해봤어!

2024-07-13 16:54 UTC, shin-mallang commented on src/test/kotlin/com/celuveat/member/adapter/in/rest/SocialLoginControllerTest.kt
> +) : FunSpec({
아하 웅 좋아!!!!

2024-07-14 02:36 UTC, merged